### ISSUE TITLE
Name conflict with Freenode sigyn

### ISSUE THREAD

**Issue by janicez** [alyx/sigyn#11]
... ?

**Comment by alyx** [comment]
And this is a bug because?

**Comment by janicez** [comment]
it's not. I'm just curious what brought you to choose the name Sigyn.

**Comment by Justasic** [comment]
iirc it was a latin word of some sort. Alyx at the time liked words from dead languages.

**Comment by alyx** [comment]
Oh, that’s valid. Freenode and I both had the same naming scheme: Norse deities.
